### ISSUE TITLE
Configure bypass cache when not reachable.

### ISSUE THREAD

**Issue by PabloThiele** [sixhours-team/memcached-spring-boot#44]
Hi folks, 
I got some interesting situation on my environment, your lib is great and works fine, but when I make some changes on the memcached infra (changed IP or the machine become unavailable) I got troubles.
The Spring will try to connect as usual but fail in sequence, the app are able to startup anyway, but all requests are now failing because it cannot reach the cache. There are some configuration to simply ignore the cache at all if took the timeout? Since this kind of problem can happen and my app should keep going without the cache. :)

I got errors like: 
```
2018-07-09 12:54:26.947 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=/HOST:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:880)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:531)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1685)
2018-07-09 12:54:26.949 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=/HOST:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 3.
2018-07-09 12:54:27.331  INFO 4387 --- [  XNIO-2 task-1] io.undertow.servlet                      : Initializing Spring FrameworkServlet 'dispatcherServlet'
2018-07-09 12:54:27.332  INFO 4387 --- [  XNIO-2 task-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2018-07-09 12:54:27.378  INFO 4387 --- [  XNIO-2 task-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 46 ms
2018-07-09 12:54:27.543  INFO 4387 --- [  XNIO-2 task-1] io.sicredi.troubleshoot                  : Calling URI: /cooperatives
2018-07-09 12:54:27.640 WARN net.spy.memcached.MemcachedConnection:  Could not redistribute to another node, retrying primary node for cooperative:postalCodes:namespace.
2018-07-09 12:54:30.144  INFO 4387 --- [  XNIO-2 task-1] io.sicredi.troubleshoot                  : Method execution completed
2018-07-09 12:54:30.145  INFO 4387 --- [  XNIO-2 task-1] io.sicredi.troubleshoot                  : Method execution time: 2601 milliseconds.
2018-07-09 12:54:30.158 ERROR 4387 --- [  XNIO-2 task-1] io.sicredi.troubleshoot                  : Exception has been thrown by service

net.spy.memcached.OperationTimeoutException: Timeout waiting for value: waited 2.500 ms. Node status: Connection Status { /HOST:11211 active: false, authed: true, last read: 15.681 ms ago /HOST:11211 active: false, authed: true, last read: 15.668 ms ago }
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1483) ~[elasticache-java-cluster-client-1.1.1.jar:1.1.1]
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1499) ~[elasticache-java-cluster-client-1.1.1.jar:1.1.1]
```

I'm using:
Spring Boot ::        (v1.5.7.RELEASE) 
compile group: 'io.sixhours', name: 'memcached-spring-boot-starter' version 1.3.0
HOST == my real host IP

I just want to be sure that can have the bypass, maybe a Spring config to just keep going when Memcached instances goes down.

**Comment by igorbolic** [comment]
Hi Pablo, and sorry for the late response. 

Since version **1.2.0** the library supports reloading of the  Memcache configuration via Spring Boot Actuator, without the need to restart the application. 

To reload you application's configuration (with your new Memcached host IP), it is sufficient to send an POST request to Actuator's `/refresh` endpoint, or via JMX. You can find out more about `@RefreshScope` beans [here](https://cloud.spring.io/spring-cloud-static/docs/1.0.x/spring-cloud.html#_refresh_scope). 

We will soon update our demo projects to show how this feature can be used with the Spring Boot applications.

**Comment by PabloThiele** [comment]
Thanks for your response Igor! 
I got your point and it will solve the migration problem, but imagine that after the migration (bean refreshed and working fine with new IP information) the memcached server goes down. A new request will try to connect and eventually will take a time out similar of the above listed. For that specific situation , we have some tweak ? If not I'll be willing to deep on the code and try to figure out an optional configuration in a PR. :)

**Comment by celadaguido** [comment]
what about this https://dzone.com/articles/safeguard-spring-app-from-cache-failure ?

**Comment by davidkarlsen** [comment]
I am also seeing problems if restarting pods - the spy driver does not seem to be able to reconnect correctly. This is also mentioned here: https://devcenter.heroku.com/articles/memcachier#java - should you maybe switch client libs?

**Comment by sasabolic** [comment]
Thanks for reporting. We'll definitely take look at this issue.

**Comment by igorbolic** [comment]
Closing the issue since from **2.0.0** version client has been changed to XMemcached
